language: node_js
node_js:
  - "8.11.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - yarn global add gulp
script: gulp ci
addons:
  firefox: "45.0"
cache:
  yarn: true
  directories:
    - node_modules
