language: node_js
node_js:
  - "8.11.1"
services
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
before_script:
  - yarn global add gulp
script: gulp ci
addons:
  firefox: "45.0"
cache:
  yarn: true
  directories:
    - node_modules
