name: Tests

on: pull_request
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 'latest'
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn test
